### ISSUE TITLE
Cannot register custom long date formats

### ISSUE THREAD

**Issue by vernak2539** [moment/momentjs.com#121]
I'm trying to set custom long date formats using [this documentation](http://momentjs.com/docs/#/customization/long-date-formats/) and moment v2.7, but it doesn't seem to be working. 

I've put an example below. Am I doing something wrong? I've tried replacing "C" with "LLLLL" and various other values, but it always returns something like this, `moment().format( 'C' ); // "C"`

``` js
moment.lang( 'en', {
    longDateFormat: {
        LT: "h:mm A",
        L: "MM/DD/YYYY",
        LL: "MMMM Do YYYY",
        LLL: "MMMM Do YYYY LT",
        LLLL: "dddd, MMMM Do YYYY LT",
        C: 'MM YYYY MM YYYY'
    }
});
```

**Comment by kentor** [comment]
Actually, I have the exact same issue with japanese. How can we specify that we want 'MM YYYY' in english and 'YYYY MM' in japanese? Did you even fix this problem?

**Comment by vernak2539** [comment]
@kentor we abstracted the date formatting function we used, but it could be as simple as below:

```js
var lang = moment.locale();

if(lang === 'ja') {
  // format japanese
} else if(lang === 'en') {
 // format english
} else {
  // format other
}
```

**Comment by asifrafeeq** [comment]
i am getting the following error
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Error
    at Function.createFromInputFallback (http://localhost:8000/js/moment-with-locales.js:740:36)
    at configFromString (http://localhost:8000/js/moment-with-locales.js:820:32)
    at configFromInput (http://localhost:8000/js/moment-with-locales.js:1347:13)
    at prepareConfig (http://localhost:8000/js/moment-with-locales.js:1334:13)
    at createFromConfig (http://localhost:8000/js/moment-with-locales.js:1301:44)
    at createLocalOrUTC (http://localhost:8000/js/moment-with-locales.js:1379:16)
    at local__createLocal (http://localhost:8000/js/moment-with-locales.js:1383:16)
    at utils_hooks__hooks (http://localhost:8000/js/moment-with-locales.js:10:29)
    at checkDate (http://localhost:8000/player/create/2:140:42)
    at HTMLInputElement.<anonymous> (http://localhost:8000/player/create/2:131:13)


   function checkDate(){
        var sixmonths = moment.duration(6, 'M').humanize();
        var expirydate = $("#expdate").val();
        var today = moment().format('L');
        var dt = moment(expirydate).diff(moment(today));
        var expDatRes = moment.duration(dt).humanize();
        //alert(expDatRes);
        if(expDatRes <= sixmonths){
            var msg = "Your Passport Expiry Date should be greater than 6 months";
            $(".ppExpAlert").html(msg);
        }else{
            $(".ppExpAlert").html("");
        }
   }


any help is highly appreciated...

**Comment by mj1856** [comment]
@asifrafeeq - and somehow you think commenting on a 5 month old, closed, and unrelated issue will get you help?  At least log here: https://github.com/moment/moment/issues  though if you read the issue mentioned in your error message you will understand what you need to do.
