### ISSUE TITLE
isValid returns true on non date string in chrome.

### ISSUE THREAD

**Issue by rehanumar** [moment/momentjs.com#670]
Hi, I have experienced that isValid returns `true` in chrome for following string.
`moment("Non-food department experience G-1").isValid()`
on Firefox this returns `false`.

**<<edit>>**
Chrome:
`new Date('Non-food department experience G-1')`
`Mon Jan 01 2001 00:00:00 GMT+0500 (Pakistan Standard Time)`

adding a space separated number in v8 returns a valid date object. affected envs are chrome, node and v8 specific envs.

`momentjs` seems to be cool and stable as always. I am reporting that bug to v8 team. do let me know, if I need to remove or close that bug.

**Comment by marwahaha** [comment]
Thanks for the report.

There is a warning regarding this, which you should see the first time it happens. It mentions that the functionality is not reliable across all browsers and versions.
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Non-food department experience G-1, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://momentjs.com/static/js/global.js:319:25)
    at configFromString (https://momentjs.com/static/js/global.js:2536:19)
    at configFromInput (https://momentjs.com/static/js/global.js:2978:13)
    at prepareConfig (https://momentjs.com/static/js/global.js:2961:13)
    at createFromConfig (https://momentjs.com/static/js/global.js:2928:44)
    at createLocalOrUTC (https://momentjs.com/static/js/global.js:3022:16)
    at createLocal (https://momentjs.com/static/js/global.js:3026:16)
    at hooks (https://momentjs.com/static/js/global.js:16:29)
    at <anonymous>:1:2
```
